[workspace]
resolver = "2"
members = [
    "identity-registry",
    "identity-registry/meta",
    "validation-registry",
    "validation-registry/meta",
    "reputation-registry",
    "reputation-registry/meta"
]
